/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author hellk
 */
public class guiReceitas extends javax.swing.JFrame {

    /**
     * Creates new form guiReceitas
     */
    public guiReceitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmSalvarReceita = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPreparo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtModoServir = new javax.swing.JTextArea();
        btmCancelarCategoria = new javax.swing.JButton();
        btmEditarModoServir = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIngredientes = new javax.swing.JList<>();
        btmOkModoServir = new javax.swing.JButton();
        btmEditarPreparo = new javax.swing.JButton();
        btmCancelarModoServir = new javax.swing.JButton();
        btmAddIngrediente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btmRemoveIngrediente = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        btmOkPreparo = new javax.swing.JButton();
        btmRemoveCategoria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btmCancelarPreparo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btmAddCategoria = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblUnidade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btmSalvarReceita.setText("Salvar");

        txtPreparo.setColumns(20);
        txtPreparo.setRows(5);
        jScrollPane1.setViewportView(txtPreparo);

        txtModoServir.setColumns(20);
        txtModoServir.setRows(5);
        jScrollPane3.setViewportView(txtModoServir);

        btmCancelarCategoria.setText("Cancelar");

        btmEditarModoServir.setText("Editar");

        txtNome.setText("jTextField1");

        txtIngredientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(txtIngredientes);

        btmOkModoServir.setText("Ok");

        btmEditarPreparo.setText("Editar");

        btmCancelarModoServir.setText("Cancelar");

        btmAddIngrediente.setText("+ Ingrediente");
        btmAddIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAddIngredienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Categoria");

        btmRemoveIngrediente.setText("- Ingrediente");
        btmRemoveIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRemoveIngredienteActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btmOkPreparo.setText("OK");

        btmRemoveCategoria.setText("- Categoria");

        jLabel1.setText("Nome");

        btmCancelarPreparo.setText("Cancelar");

        jLabel2.setText("Preparo");

        btmAddCategoria.setText("+ Categoria");

        jLabel3.setText("Ingredientes");

        jLabel4.setText("Modo de Servir");

        lblQuantidade.setText("qtd");

        lblUnidade.setText("und");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jScrollPane1)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(btmEditarPreparo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btmOkPreparo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btmCancelarPreparo)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btmAddIngrediente)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblUnidade)
                                                    .addComponent(btmRemoveIngrediente)))
                                            .addComponent(lblQuantidade))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btmEditarModoServir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btmOkModoServir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btmCancelarModoServir))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btmAddCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btmRemoveCategoria)
                        .addGap(89, 89, 89)
                        .addComponent(btmSalvarReceita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btmCancelarCategoria)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantidade)
                            .addComponent(lblUnidade))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmEditarPreparo)
                    .addComponent(btmOkPreparo)
                    .addComponent(btmCancelarPreparo)
                    .addComponent(btmAddIngrediente)
                    .addComponent(btmRemoveIngrediente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmEditarModoServir)
                    .addComponent(btmOkModoServir)
                    .addComponent(btmCancelarModoServir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmRemoveCategoria)
                    .addComponent(btmAddCategoria)
                    .addComponent(btmSalvarReceita)
                    .addComponent(btmCancelarCategoria)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmAddIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAddIngredienteActionPerformed
        // TODO add your handling code here:
        JFrame frame = new guiSelecionarIngrediente();
        frame.setVisible(true);
    }//GEN-LAST:event_btmAddIngredienteActionPerformed

    private void btmRemoveIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRemoveIngredienteActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btmRemoveIngredienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiReceitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmAddCategoria;
    private javax.swing.JButton btmAddIngrediente;
    private javax.swing.JButton btmCancelarCategoria;
    private javax.swing.JButton btmCancelarModoServir;
    private javax.swing.JButton btmCancelarPreparo;
    private javax.swing.JButton btmEditarModoServir;
    private javax.swing.JButton btmEditarPreparo;
    private javax.swing.JButton btmOkModoServir;
    private javax.swing.JButton btmOkPreparo;
    private javax.swing.JButton btmRemoveCategoria;
    private javax.swing.JButton btmRemoveIngrediente;
    private javax.swing.JButton btmSalvarReceita;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JList<String> txtIngredientes;
    private javax.swing.JTextArea txtModoServir;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtPreparo;
    // End of variables declaration//GEN-END:variables
    private void liberarCampos() {
    
        txtNome.setEditable(true);
        txtPreparo.setEditable(true);
        txtModoServir.setEditable(true);
        
   }

    public void bloquearCampos(){
        
        limparCampos();
        txtNome.setEditable(false);
        txtPreparo.setEditable(false);
        txtModoServir.setEditable(false);
    }
    
    public void limparCampos(){
        
          txtNome.setText(" ");
        txtPreparo.setText(" ");
        txtModoServir.setText(" ");

    }
private void btmPreparoStartSet() {
    
        btmCancelarPreparo.setEnabled(false);
        btmEditarPreparo.setEnabled(true);
        btmOkPreparo.setEnabled(false);

    }

    private void btmPreparoEditSet() {
    
        btmCancelarPreparo.setEnabled(true);
        btmEditarPreparo.setEnabled(false);
        btmOkPreparo.setEnabled(true);
    }
    private void btmModoServirStartSet() {
    
        btmCancelarModoServir.setEnabled(false);
        btmEditarModoServir.setEnabled(true);
        btmOkModoServir.setEnabled(false);
        
    
    }

    private void btmModoServirEditSet() {
    
       btmCancelarModoServir.setEnabled(true);
        btmEditarModoServir.setEnabled(false);
        btmOkModoServir.setEnabled(true);
    }
    
    
}
